version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_DSN: >
        host=postgres_db
        user=${POSTGRES_USER}
        password=${POSTGRES_PASSWORD}
        dbname=${POSTGRES_DB}
        port=${POSTGRES_PORT}
        sslmode=disable
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
      JWT_SECRET: ${JWT_SECRET}
      WEBHOOK: ${WEBHOOK}
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/postgres_init-extensions.sql:/docker-entrypoint-initdb.d/postgres_init-extensions.sql:ro
      - ./scripts/pg_healthcheck.sh:/usr/local/bin/pg_healthcheck.sh:ro
    healthcheck:
      test: [ "CMD", "/usr/local/bin/pg_healthcheck.sh" ]

volumes:
  postgres-data:
